#!/bin/php
<?php

require 'vendor/autoload.php';

use Symfony\Component\Console\Application;
use Wsl\CourseManager\Commands\CreateProjectCommand;
use Wsl\CourseManager\Commands\RemoveProjectCommand;
use Wsl\CourseManager\Commands\UninstallCommand;

$app = new Application('Course manager', '1.0');

//Register commands

$app->add(new CreateProjectCommand('add:project'));
$app->add(new RemoveProjectCommand('remove:project'));
$app->add(new UninstallCommand('uninstall'));


$app->run();
