#!/usr/bin/php
<?php

/**
 * Script de création d'un nouveau cours.
 * Ex: course-create mydigitalschool b3 mvc
 *
 * @package wsl
 */

// require 'vendor/autoload.php';

// use Wsl\CourseManager\Env;
// use Wsl\CourseManager\Course;
// use Wsl\CourseManager\Console;
// use Wsl\CourseManager\FileManager;

// if ($argc < 3) {
//     Console::print("Nombre d'arguments insuffisants. cm-add-module [vendor] [level] coursename modulename");
//     exit;
// }

// $env = Env::create();

// $courseName = $argv[1];

// $courses = FileManager::listCoursesByVendor();

//Rechercher parmi les vendor un cours avec le nom courseName (avec ou sans le niveau)
//S'il y'en a plusieurs, on ne peut pas discriminer il faut ajouter [vendor].
//S'il y'en a plusieurs, on ne peut pas discriminer il faut ajouter [level].
