#!/usr/bin/php
<?php

/**
 * Script de création d'un nouveau cours.
 * Ex: course-create mydigitalschool b3 mvc
 *
 * @package wsl
 */

require 'vendor/autoload.php';

use Wsl\CourseManager\Env;
use Wsl\CourseManager\Course;
use Wsl\CourseManager\Console;

if ($argc < 3) {
    Console::print("Nombre d'arguments insuffisants. cm-create vendor level coursename");
    exit;
}

$course = new Course(
    Env::create(),
    $argv[1],
    $argv[2],
    $argv[3]
);

//Initialisation du contenu du dossier du cours
$course->createCourseDirectory();
