#!/usr/bin/php
<?php

/**
 * Script de création d'un nouveau cours. 
 * Ex: course-create mydigitalschool b3 mvc
 *
 * @package wsl 
 */

require 'vendor/autoload.php';

use Wsl\CourseManager\Env;
use Wsl\CourseManager\Course;

$env = Env::create();

if ($argc < 3) {
    $env->print("Nombre d'arguments insuffisants. create-course [option] vendor level coursename");
    exit;
}

$course = new Course(
    $argv[1],
    $argv[2],
    $argv[3]
);

//Création du dossier du cours
$env->mkdirp($course->path());

//Initialisation du contenu du dossier du cours
$env->prepareDirectory($course);
