#!/usr/bin/php
<?php

/**
 * Script de création d'un nouveau cours. 
 * Ex: create-course mydigitalschool b3 mvc
 *
 * @package wsl 
 */

require 'vendor/autoload.php';

use Wsl\CourseManager\Env as Env;
use Wsl\CourseManager\Course as Course;

$env = Env::create();

var_dump($env->envVariables);


// if ($argc < 3) {
//     Env::print(sprintf("Nombre d'arguments insuffisants. ./create-course [option] vendor level coursename"));
//     exit;
// }

// $course = new Course(
//     $argv[1],
//     $argv[2],
//     $argv[3]
// );

// //Création du dossier du cours
// Env::mkdirp($course->vendor);
// Env::mkdirp($course->fullName());

// //Initialisation du contenu du dossier du cours
// Env::prepareDirectory($course);
